### ISSUE TITLE
ICMP Ping

### ISSUE THREAD

**Issue by capriciousduck** [statping-ng/statping-ng#105]
My server is online but an ICMP Ping request from Statping always says that the host is offline even when it's online. What do I do now?

**Comment by adamboutcher** [comment]
Can you provide a log?
How are you deploying Statping?

**Comment by jemand771** [comment]
also, this probably doesn't affect you, but there _are_ ways for a ping to fail even if the host is up:
* some sort of firewall rejects outgoing ICMP (I've had that at work before)
* the target machine could actively refuse to answer the ping

so, just to be sure, could you check if you can successfully ping the target host from the same machine/network that statping is deployed on?

**Comment by maxzapp** [comment]
I ran it on a docker and can also not use ping, but i am new to it, so maybe my fault.

**Comment by adamboutcher** [comment]
Could you try starting a different container? I think the whoami ones have ping.

**Comment by maxzapp** [comment]
I using another container to ping 8.8.8.8 and it is working. From within statping-Ng i got a permission denied(are you root) error.
su -  is not working

**Comment by CorneliousJD** [comment]
> I using another container to ping 8.8.8.8 and it is working. From within statping-Ng i got a permission denied(are you root) error. su - is not working

When running the container change the "--user 99:100" to "--user 0:0" to run as root and allow pings.
If you're running on unraid you'll need to toggle the "advanced" tab in the docker container page, and and edit/add this under "Extra Parameters"

**Comment by maxzapp** [comment]
Great advice, yes I run docker on Unraid I changed the setting and it worked immediately 

Many Thanks

**Comment by almereyda** [comment]
An upstream issue at https://github.com/go-ping/ping/issues/123 suggests to set:

```console
sysctl -w net.ipv4.ping_group_range="0 2147483647"
```

Which, unfortunately, doesn't have much effect on the container when set on the host.

Adding

```yaml
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
```

to a Compose service definition allowed the container to send ICMP pings.
