### ISSUE TITLE
Invalid notification

### ISSUE THREAD

**Issue by brunomiranda-hotmart** [statping-ng/statping-ng#107]
Regarding my issue https://github.com/statping-ng/statping-ng/issues/80, is there any update in the foreseable feature?
This bug is really bugging the devs on my company.
And from what I could tell #67 fixed this issue.

**Comment by adamboutcher** [comment]
I can look at pushing to unstable next week for a test build. Sorry I've been busy with work.

**Comment by adamboutcher** [comment]
This was merged into unstable today and we're hopefully going to have a test build later today/tomorrow.
