### ISSUE TITLE
empty homepage

### ISSUE THREAD

**Issue by aikozijlemans** [statping-ng/statping-ng#112]
I get the following issue on lan ip with port of the docker container `http://192.168.2.11:19280`

TypeError: Cannot read properties of undefined (reading 'call')
    at u (bundle.js:1)

**Comment by adamboutcher** [comment]
Hi, see issue https://github.com/statping-ng/statping-ng/issues/62 and see if that resolves it...

**Comment by aikozijlemans** [comment]
Thank you that fixed the issue!
