### ISSUE TITLE
Windows Builds Fail

### ISSUE THREAD

**Issue by adamboutcher** [statping-ng/statping-ng#12]
Windows Builds Fail

**Comment by jonathanrbarney** [comment]
if you look at the ![actions result](https://user-images.githubusercontent.com/49847521/130189493-a851205b-de43-49c4-943d-14fa4f5d4cfc.png) I think only the windows run failed, and it failed on a move, not even a compile. I think the name is just different than the script is expecting.

**Comment by jonathanrbarney** [comment]
![Screenshot from 2021-08-19 23-23-02](https://user-images.githubusercontent.com/49847521/130189926-ab0ef844-e1ed-4ef4-b59e-5877e6a033c8.png)

**Comment by jonathanrbarney** [comment]
I think the name is different that what it had expected in the mv command.

**Comment by adamboutcher** [comment]
Looks like it was a missing build flag and the copy/compress section is the part the triggered the actual fail condition even though the build part didn't end cleanly. 

Commit 62929e618eafb6714dda6db0067c8b8465d618b9 fixed this in the quick dev test actions, and I've pushed it into the stable build actions too.
