### ISSUE TITLE
[Feature Request] Script tag support for Footer/Head

### ISSUE THREAD

**Issue by Fireant456** [statping-ng/statping-ng#130]
It would be good to be able to throw google analytics and other scripts into the header/footer. This would require that a header html field be added in the control panel and allow for script tags in the footer field as well as the proposed header config field.

Currently, we try a `document.write(new Date())` in our Copywrite notice in the footer but that fails to actually run. I would like to replace the text Name in the header of the page with our logo but I cannot seem to find an easy way to do this. I could easily do this with JS script tags in the header or even in the footer, but as mentioned before it appears the script tags do not function.

**Comment by adamboutcher** [comment]
See #137.

Once those changes are merged then we will support custom base templates meaning custom tags can be included.
