### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by ku1918** [statping-ng/statping-ng#131]
Is statping doesn't recognize system environment variables for proxy?

HTTP_PROXY
HTTPS_PROXY
http_proxy
https_proxy

I have configured all the said system environment variables but statping-ng still doesn't use them.

**Comment by dkellenb** [comment]
Seems to be related to https://github.com/statping/statping/issues/624

**Comment by adamboutcher** [comment]
Not sure it's supported, hopefully we can figure this out (eventually).

**Comment by vintury** [comment]
In latest 0.90.80 release proxy worked incorrectly.
I create pull request for fix this. But them rejected (

If you manually build statping docker image, you can fix file utils.go:
https://github.com/statping-ng/statping-ng/pull/141

**Comment by adamboutcher** [comment]
This should be merged soon and pushed into the next version.

**Comment by adamboutcher** [comment]
Will be merged into stable soon.
