### ISSUE TITLE
[Feature Request] Allow HEAD http request

### ISSUE THREAD

**Issue by vintury** [statping-ng/statping-ng#143]
Hello.
You can use HEAD request type for get service status. In latest version HEAD request type not supported.

HEAD is most lightway request type. And can be used for more often status checks. Because in response it get only HTTP headers without data.

Please add HEAD request type to statping.

**Comment by adamboutcher** [comment]
See https://github.com/statping-ng/statping-ng/issues/145

**Comment by adamboutcher** [comment]
I am aware and it is on my radar to resolve.

**Comment by sndrr** [comment]
Isn't that just adding the HEAD method to the frontend?
```
diff --git a/frontend/src/forms/Service.vue b/frontend/src/forms/Service.vue
index 32bb78a..ba165c3 100644
--- a/frontend/src/forms/Service.vue
+++ b/frontend/src/forms/Service.vue
@@ -98,6 +98,7 @@
                         <option value="DELETE" >DELETE</option>
                         <option value="PATCH" >PATCH</option>
                         <option value="PUT" >PUT</option>
+                        <option value="HEAD" >HEAD</option>
                     </select>
                     <small class="form-text text-muted">A GET request will simply request the endpoint, you can also send data with POST.</small>
                 </div>
```
And using the `http.Head` request instead of the `http.Get`?

**Comment by sndrr** [comment]
Ah, I see that it uses `http.NewRequest(method, endpoint, body)` in [utils/utils.go](https://github.com/statping-ng/statping-ng/blob/dev/utils/utils.go#L172). So I suppose, only changing it in the frontend should suffice.

**Comment by sndrr** [comment]
Tested it (by hacking the form input), and works:
![image](https://user-images.githubusercontent.com/5821198/182581451-03a30584-4a21-4bc8-b6f8-1cd6ad03d4e0.png)
