### ISSUE TITLE
can we add a toggle settings to hide the dashboard link on the homepage in settings?

### ISSUE THREAD

**Issue by gillbates** [statping-ng/statping-ng#153]
Hi Team,

thanks for the great work first of all. 
We are using this as a public page to monitor all statuses of our service.

In this case, it would be very useful if we could hide the link to dashboard on the footer part to prevent some unwanted guesses.

Can we support that?

thanks in advance!

**Comment by adamboutcher** [comment]
As a temporary fix, you can set the footer to be a blank value (such as &nbsp) and it'll remove the link.

**Comment by gillbates** [comment]
> As a temporary fix, you can set the footer to be a blank value (such as &nbsp) and it'll remove the link.

gotcha! thx @adamboutcher
