### ISSUE TITLE
Extend API

### ISSUE THREAD

**Issue by 3ele-projects** [statping-ng/statping-ng#169]
Hello,
it's a well maintained fork, thanks for that.

Is there a way to extend the API?

In the current state you can create services but the possibility to set settings is missing.

https://docs.statping.com/#request-services-create-service

Example settings would be:

follow redirects
Notify After Failures

**Comment by jemand771** [comment]
heya, this feels like a dupe to #142. please add any additional info you have there
(also, feel free to reopen if it's not and/or I missed something)

we don't really write much code ourselves and only bring in community contributions in one central place. so if you want to take a shot at implementing this - go ahead :D
