### ISSUE TITLE
Smartphone apps seems to be broken

### ISSUE THREAD

**Issue by maxzapp** [statping-ng/statping-ng#173]
Hi,

the IOS app is not in the app store available  anymore an on the Android app the screen is just white. The apps are  maybe from other owners but you still refer to them, this should corrected in my opinion.

thx
zappmax

**Comment by jemand771** [comment]
uhh yeah, as far as I know the app is pretty dead. I thought we removed all references to it, but maybe we missed some 👀 
someone somewhere™ also talked about making a new app, but I don't think anything useful has happened there yet

**Comment by adamboutcher** [comment]
Closing as we don't have any real influence on the mobile apps.

**Comment by truejp** [comment]
@jemand771 Reference is on this website: https://statping-ng.github.io/features.html
Just found this issue while looking for a fixed app LOL

**Comment by jemand771** [comment]
TIL we're running github pages :^)

**Comment by adamboutcher** [comment]
> TIL we're running github pages :^)

We do, if the iOS app is gone forever, I'll remove the link.
