### ISSUE TITLE
Statping installed via Snap -> fork/exec /bin/ping: permission denied

### ISSUE THREAD

**Issue by d34vbd5** [statping-ng/statping-ng#180]
So I have installed Statping on a fresh Ubuntu 20.04 via Snap and I am running into app armor permission problems.
Anyone know how to fix this?

sudo dmesg |grep DENIED
[  961.285336] audit: type=1400 audit(1664218529.041:33): apparmor="DENIED" operation="exec" profile="snap.statping-ng.statping" name="/bin/ping" pid=3555 comm="statping" requested_mask="x" denied_mask="x" fsuid=0 ouid=0

**Comment by jemand771** [comment]
heya, just so you know - we're not ignoring you, I just have no clue what to do about this. I don't use snap for anything (didn't even know we published snaps, lol), but maybe someone from the community has an idea 👀

**Comment by adamboutcher** [comment]
I don't know how to fix this but I suspect if apparmour is like selinux then you can add an exception.

Unless this causes issues for many others I'm closing this as it feels more like an OS problem and not a statping-ng issue.
