### ISSUE TITLE
How to configure services unattended?

### ISSUE THREAD

**Issue by opub** [statping-ng/statping-ng#194]
I would like to start an instance with a bunch of services preconfigured. Is this possible?

It might run under Docker Compose, EC2 or Kubernetes. It seems like config.yml only has the initial setup info and I would need some way to set the services and groups via yaml or json ideally.

Thanks.

**Comment by opub** [comment]
I found the documentation here https://github.com/statping-ng/statping-ng/wiki/Bulk-Import-Services.

**Comment by embeh** [comment]
How would this work for adding ICMP services?
Thank you!
