### ISSUE TITLE
Feature: Mattermost Notifications

### ISSUE THREAD

**Issue by adamboutcher** [statping-ng/statping-ng#20]
Need to test as Mattermost might be compatible with Slack...

**Comment by nilshee** [comment]
https://docs.mattermost.com/developer/webhooks-incoming.html#tips-and-best-practices

should work with no problems

**Comment by adamboutcher** [comment]
So my own Web hooks in some personal tooling I used to use for Slack didn't move to Mattermost smoothly. I'm going to try and test this and if it works add Mattermost in the documentation. If not I'll write a new notifier.

**Comment by yitian-reevo** [comment]
Looking forward to it! We are using Mattermost as well and planning to integrate it to statping

**Comment by adamboutcher** [comment]
The slack webhook didn't work.
I'm currently testing some basic integration now.

**Comment by adamboutcher** [comment]
I've pushed this to `dev` branch; you can test it via the artifacts https://github.com/statping-ng/statping-ng/actions/runs/1233659094 once it's built.
We will look at a release to unstable soon.
