### ISSUE TITLE
IOS APP Not available in France

### ISSUE THREAD

**Issue by zamk-paw** [statping-ng/statping-ng#209]
Hello, i think everything is in the title, the app isn't available in France.

When i click on the link to redirect to the ios app it says its not available !

Can you try to fix it please ? i would loved to use it !

Thanks for reading,
Mathéo.

**Comment by jemand771** [comment]
Hi there,
we're not maintaining the ios app. we don't have the original code _and_ none of use know how to make ios apps and/or have an iphone to test. sorry :(

as always, we're open to contributions but remaking the whole app would be a lot of work. I don't see native apps coming back any time soon

**Comment by jemand771** [comment]
other users have also reported the app as not being available in some places (#29), no clue what's up with that 👀
