### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by kroese** [statping-ng/statping-ng#221]
This project started because the original statping didn't saw development anymore. 

But now it has been a year since the last release, pull requests aren't getting merged, etc.

So is this project dead now, just like its predecessor?

**Comment by jemand771** [comment]
wellll, not really. things haven't really worked out the way we planned, but we're still here 👀
adam got held up with work and health stuff a lot iirc, and I'm just a massive procrastinator (sorry)

The main thing blocking us is me remaking the github actions workflows. I'm almost done™, but you know, last 20% of work take 80% of effort. (waiting 10 minutes only to see you've misspelled something is _not_ fun)

Also, we've said this before but neither of us know go (or the statping codebase) well enough to make our own contributions, at least not larger ones. I definitely plan on reviewing+merging as much as I can as soon as I'm done with the CI stuff. as always, all contributions are welcome

sorry it's taking this long, and thanks for being patient D:
