### ISSUE TITLE
Cannot use mobile app

### ISSUE THREAD

**Issue by RobinDev03** [statping-ng/statping-ng#236]
Today I set up statping-ng on a new mashine. Whe I tried to connect the app with it, i entered the API-Key from the User and the IP with http:// in the app, because the QR-Code seems to be wrong... In the textfield above aren't any data. Whe I tried to connect with the credentials, I entered, it always leeds me to the statpng default demo instance...

**Comment by jemand771** [comment]
we don't have the app source code and also no device to try it - consider the app dead. sorry :(
