### ISSUE TITLE
Statping takes wrong DNS Server in Splitunnel VPN

### ISSUE THREAD

**Issue by MrFly72** [statping-ng/statping-ng#238]
I have a device that has a split tunnel.
Specific 10.x IPs will be used through a VPN, but the major traffic is using my home-internet connection.
If I am starting the windows version of statping, it will do a DNS query, but it will take the DNS-Server from the VPN instead of the one that is system default (which is the home-internet-connection).
This leads to all URL not being resolved by the DNS, as the VPN-DNS does not resolve any internet-addresses.
One solution for this would be to be able to set the DNS Server that will be used for the DNS query.

**Comment by adamboutcher** [comment]
I think this is an issue with your OS/deployment method. I'd try a container and forcing the networking / gateway down the interface you want.

**Comment by adamboutcher** [comment]
Feel free to discuss if you need.

**Comment by MrFly72** [comment]
Hi. I can only take the interface down by disconnecting the VPN Tunnel. But that tunnel is needed for all intranet addresses of my company. 
There are two adapters active at all times with a vpn. And with split tunnels both adapters are actively used. Both have DNS and they will be called both. First the VPN one, then the main one by the OS. But it seems that statping queries the adapter and takes the DNS Server from there and will not use OS functions?
Eg. A resolve-dnsname from powershell does it right in that scenario.
