### ISSUE TITLE
How to check uptime of HTTP URL returning application/octet-stream

### ISSUE THREAD

**Issue by a-camacho** [statping-ng/statping-ng#24]
Hi guys,

I'm using your software, instead of the original one, but had a question I am not being able to resolve on either.
I would like to monitor an HTTP URL that gives me Content-Type=application/octet-stream.

If I do a curl on bash, I get a 200 response code.

```
curl -i https://domain.ext/mypath
HTTP/2 200 
content-type: application/octet-stream
date: Fri, 27 Aug 2021 06:51:55 GMT
```

But if I add service to statping it always tells me that it is down.

![image](https://user-images.githubusercontent.com/29976133/131085218-1e317f2f-505a-4aa3-9277-1825e15e80f4.png)

What options, headers and body regex should I be using to be able to monitor this flux ?
I would like to be sure that status_code = 200 and content_type = application/octet-stream, to set the service as "online".

Anyone has any clue ?
Thank you very much.

**Comment by adamboutcher** [comment]
I'm not sure as I don't use that feature but is there an option to do a head request instead of get?

That might work as I suspect the get request is trying to pull the entire stream and not just part of it.

**Comment by adamboutcher** [comment]
So there isn't a HEAD option, We'll look into adding it.

**Comment by adamboutcher** [comment]
Note to self.

Try adding HEAD for http service. 
https://github.com/statping-ng/statping-ng/blob/dev/frontend/src/forms/Service.vue

**Comment by sndrr** [comment]
See PR #159. That will close this issue.

**Comment by adamboutcher** [comment]
Hi @a-camacho

Can you try testing with one of the artifacts from the PR test? https://github.com/statping-ng/statping-ng/actions/runs/2796514658
Feel free to recreate a new issue if this doesn't solve it.

We will merge into stable eventually.
