### ISSUE TITLE
Docker Release

### ISSUE THREAD

**Issue by WilliamRoxit** [statping-ng/statping-ng#261]
Hi,

it's been two years since there was a new release. Are there any plans to release a new version shortly? It still is a great project, and I see that one of our main issues (unable to login with non-admin user) has been fixed.

**Comment by jemand771** [comment]
there's still some stuff wrong with the way release versions are generated and I was just too scared to try it until now. I guess I'll run a build and see what breaks 😅

**Comment by WilliamRoxit** [comment]
Yeah sometimes that's the best thing to try :D

**Comment by kroese** [comment]
@WilliamRoxit I build Docker images for every Statping release: https://hub.docker.com/r/dockurr/statping

**Comment by jemand771** [comment]
if you're fine with some fiddling around, all pushes also get built as OCI images already - github actions jobs (e.g. [latest release attempt](https://github.com/statping-ng/statping-ng/actions/runs/7397045532/artifacts/1145260798)) have a `docker-images` artifact you can download, unzip, and load/push/convert the contained `image.tar` using your favorite image tool like [skopeo](https://github.com/containers/skopeo) or [crane](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane.md)

that's just the last part that's missing for _proper_ automated docker releases here - `docker load` can't handle multiplatform/OCI images - found that out the hard way, lol

**Comment by jemand771** [comment]
v0.91.0 is out! 🎉 (hey, I fixed my broken actions)

get the binaries from the [GitHub release](https://github.com/statping-ng/statping-ng/releases/tag/v0.91.0) or docker images from your [friendly neighbourhood docker registry](https://github.com/statping-ng/statping-ng/pkgs/container/statping-ng) - `ghcr.io/statping-ng/statping-ng:0.91.0`
