### ISSUE TITLE
iOS App UK

### ISSUE THREAD

**Issue by ghost** [statping-ng/statping-ng#29]
Any plans for the iOS app to be available in the UK store.

It wont let me download it and says its not available in my region!

**Comment by jemand771** [comment]
Sorry to hear you're having issues, but we're not related to the iOS app at all 👀
~You could ask over at the [original repo](https://github.com/statping/statping) but there hasn't been any activity there in the last couple of months.~

Are you sure it's a geo-restriction and not just a weirdly worded error message? The app not being available in the UK sounds odd to me (why wouldn't it?)
@adamboutcher you're from the uk right? do you have an IPhone to test this by any chance? ^^

**Comment by adamboutcher** [comment]
I don't have an iPhone / iPad to test with. Sorry.

**Comment by adamboutcher** [comment]
Labelled as wontfix as we don't actually have the app source code.
