### ISSUE TITLE
Wrong reference in docker-compose

### ISSUE THREAD

**Issue by marcbria** [statping-ng/statping-ng#38]
Docker compose refers to a repository that does not exist in dockerHub:
https://github.com/statping-ng/statping-ng/blob/7834d1f872f160f3fc6f796192f6f2aa3fdc1762/docker-compose.yml#L6

Changed to "adamboutcher/statping-ng" did the job.

**Comment by marcbria** [comment]
Sorry for the noise.
I checked in the wrong branch.
Fixed in dev.

**Comment by adamboutcher** [comment]
This should be fixed in stable too now.
