### ISSUE TITLE
Fix "Uptime last" text in the UI

### ISSUE THREAD

**Issue by amard33p** [statping-ng/statping-ng#58]
This is an existing issue in statping. PRs exist but have not been merged

original issue:
https://github.com/statping/statping/issues/868
PRs addressing it:
https://github.com/statping/statping/pull/919
https://github.com/statping/statping/pull/891

Please merge either of the PRs.

_note: I edited in the other upstream PR that references the issue. hope you don't mind. ~@jemand771_

**Comment by dimatha** [comment]
@adamboutcher are you guys planing to push that new image? Thanks!

**Comment by adamboutcher** [comment]
No eta, I didn't think we merged enough changes to warrant a version push but we can do our people want.
