### ISSUE TITLE
"View Service" API Request don't return service "type"

### ISSUE THREAD

**Issue by maurettoXD** [statping-ng/statping-ng#61]
As in object, the api request called with "{{endpoint}}/api/services/SERVICEID" don't return the "type" of the service (http, icmp, tcp, ecc)

Can be useful to add this, for example for perform mass updating, by api, of just some kind of service.

**Comment by jonathanrbarney** [comment]
Could you provide some more details of the request that you are making and not seeing `type`? 

For a bit more context in order to view certain object fields through the API you must provide authentication. While it is true that an unauthenticated user will not be able to see `service.type` providing either user or admin level of auth the GET request should allow you to see this field through the API. If you are supplying valid auth and the `type` is not appearing then that is a bug.

**Comment by maurettoXD** [comment]
Of course i use autenticated call.

I use code according to this:

https://documenter.getpostman.com/view/1898229/SzmfXwi4?version=latest#8e8948f7-4015-48c4-b32e-c11caab5d31f

From both curl and python i get the same results.

![2021-10-21_12-39](https://user-images.githubusercontent.com/32866094/138261967-7f73d7e2-ff91-4e82-89e8-c6ca4a1fbb6b.png)

As you can see, it's missing the service type.

Thanks

**Comment by jonathanrbarney** [comment]
I have just tested with the latest release and the following curl request and received the following response which does include type.

`curl --request GET \
  --url http://localhost:8080/api/services/1 \
  --header 'Authorization: Bearer <key>'`

`{
  "allow_notifications": true,
  "avg_response": 1032130,
  "check_interval": 10,
  "checkins": [
    {
      "id": 1,
      "service_id": 1,
      "name": "Demo Checkin 1",
      "interval": 3,
      "api_key": "demoCheckin123",
      "created_at": "2021-10-21T11:02:52.790465095Z",
      "updated_at": "2021-10-21T11:02:52.790465095Z",
      "failing": false,
      "last_hit": "2021-10-21T10:59:52.793074012Z",
      "hits": [
        {
          "id": 1,
          "from": "192.168.0.1",
          "created_at": "2021-10-21T10:59:52.793074012Z"
        }
      ],
      "failures": []
    }
  ],
  "created_at": "2021-07-23T11:02:52.778616751Z",
  "domain": "https://google.com",
  "expected": "",
  "expected_status": 200,
  "failures": null,
  "failures_24_hours": 320,
  "group_id": 1,
  "grpc_health_check": false,
  "headers": "",
  "id": 1,
  "incidents": [],
  "last_error": "2021-10-28T04:22:52.795400335Z",
  "last_success": "2021-10-21T11:05:14.625632229Z",
  "latency": 288718,
  "messages": [
    {
      "id": 1,
      "title": "Routine Downtime",
      "description": "This is an example a upcoming message for a service!",
      "start_on": "2021-10-21T11:17:52.787926949Z",
      "end_on": "2021-10-21T13:02:52.787927119Z",
      "service": 1,
      "notify_users": null,
      "notify_method": "",
      "notify_before": null,
      "notify_before_scale": "",
      "created_at": "2021-10-21T11:02:52.78797292Z",
      "updated_at": "2021-10-21T11:02:52.78797292Z"
    }
  ],
  "method": "GET",
  "name": "Google",
  "notify_after": 3,
  "notify_all_changes": true,
  "online": true,
  "online_24_hours": 88.93,
  "online_7_days": 95.34,
  "order_id": 1,
  "permalink": "google",
  "ping_time": 2747,
  "port": 0,
  "post_data": "",
  "public": true,
  "redirect": true,
  "stats": {
    "failures": 403,
    "hits": 8657,
    "first_hit": "2021-10-18T11:02:52.872111834Z"
  },
  "status_code": 200,
  "timeout": 10,
  "tls_cert": "",
  "tls_cert_key": "",
  "tls_cert_root": "",
  "type": "http",
  "updated_at": "2021-10-21T11:02:52.778737833Z",
  "verify_ssl": true
}`

**Comment by maurettoXD** [comment]
I updated to later version and now it's work! Sorry and thanks for support <3
