### ISSUE TITLE
Unable to login as admin - stuck loading

### ISSUE THREAD

**Issue by maurettoXD** [statping-ng/statping-ng#66]
We notice that after some week from a fresh installation, both sqlite and mysql, we are unable to login as admin, this remain in loading state forever.

We notice that also the home page of statping, the one showing all service status, remain in loading state forever.

Checking logs, stateping is working normally, it's checking service and so on, but we still face this problem.

We have many services, a mysqldump it's around 70mb, machine load and resources are good.

**Comment by maurettoXD** [comment]
Deleted about 500.000 records from "hits" table now all is working fine...but my hits table still huge :)

**Comment by adamboutcher** [comment]
Do you know what the hits table shows?

I've jad this issue too but never looked into it.

**Comment by maurettoXD** [comment]
Attached a screenshot of what's in "hits" table.

It seems that in this table there are any hits made to a service, i think needed for to make the historical graphs of them.

I think for to fix this problem we need to create kind of "hits_history" table and move in this new table the records from "hits" table every day (or every N days) or more simply, create a user config "RETENTION DAYS" that delete record older than N days.

![2021-11-03_22-01](https://user-images.githubusercontent.com/32866094/140192127-d3ab2cef-9ef9-42b6-b9fb-0b8353443fc8.png)
