### ISSUE TITLE
ICMP Ping timeout setting not working on macos

### ISSUE THREAD

**Issue by livelazily** [statping-ng/statping-ng#75]
`ping -W` on linux is setting the timeout, but it has different meaning on macos: https://ss64.com/osx/ping.html

So this code will never work as expect on macos : https://github.com/statping-ng/statping-ng/blob/v0.90.78/utils/utils_custom.go#L45

**Comment by adamboutcher** [comment]
Can you find the equivalent to -w for mac OS? I don't have access to a mac to check and test?

**Comment by livelazily** [comment]
macos `ping -t timeout_in_seconds` is equivalent for `ping -W timeout_in_seconds` on linux.
The `-c` option has the same meaning on both platform
