### ISSUE TITLE
Invalid notification

### ISSUE THREAD

**Issue by brunomiranda-hotmart** [statping-ng/statping-ng#80]
My service config:
```
mysql> select id, expected_status, check_interval, check_type, method, timeout, notify_after from services where id = "113";
+-----+-----------------+----------------+------------+--------+---------+--------------+
| id  | expected_status | check_interval | check_type | method | timeout | notify_after |
+-----+-----------------+----------------+------------+--------+---------+--------------+
| 113 |             200 |             60 | http       | GET    |      30 |            5 |
+-----+-----------------+----------------+------------+--------+---------+--------------+
```

Failures:
```
mysql> select service, error_code, reason, created_at from failures where service = "113";
+---------+------------+-------------+---------------------+
| service | error_code | reason      | created_at          |
+---------+------------+-------------+---------------------+
|     113 |        504 | status_code | 2021-12-13 20:54:39 |
|     113 |        504 | status_code | 2021-12-14 19:34:39 |
|     113 |        504 | status_code | 2021-12-14 19:49:39 |
|     113 |        504 | status_code | 2021-12-14 20:14:39 |
|     113 |        504 | status_code | 2021-12-14 20:23:39 |
|     113 |        504 | status_code | 2021-12-14 20:27:39 |
|     113 |        504 | status_code | 2021-12-14 20:32:39 |
|     113 |        504 | status_code | 2021-12-14 20:35:39 |
|     113 |        504 | status_code | 2021-12-14 21:30:39 |
|     113 |        504 | status_code | 2021-12-14 22:12:39 |
|     113 |        504 | status_code | 2021-12-14 22:15:39 |
|     113 |        504 | status_code | 2021-12-14 22:57:39 |
|     113 |        504 | status_code | 2021-12-14 23:02:39 |
|     113 |        504 | status_code | 2021-12-14 23:04:39 |
|     113 |        504 | status_code | 2021-12-14 23:15:39 |
|     113 |        504 | status_code | 2021-12-14 23:27:39 |
|     113 |        504 | status_code | 2021-12-14 23:42:39 |
|     113 |        504 | status_code | 2021-12-14 23:44:39 |
|     113 |        504 | status_code | 2021-12-14 23:50:39 |
|     113 |        504 | status_code | 2021-12-15 00:20:39 |
|     113 |        504 | status_code | 2021-12-15 01:16:39 |
|     113 |        504 | status_code | 2021-12-15 01:21:39 |
|     113 |        504 | status_code | 2021-12-15 02:06:39 |
|     113 |        504 | status_code | 2021-12-15 02:29:39 |
|     113 |        504 | status_code | 2021-12-15 02:34:39 |
|     113 |        504 | status_code | 2021-12-15 03:34:39 |
|     113 |        504 | status_code | 2021-12-15 03:36:39 |
+---------+------------+-------------+---------------------+
```

As can be seen, there aren't any 5 consecutive failures, however my team was notified as if this server was off.

Is 504 a special case that instantly triggers notification? Or am I missing something?

I'm currently using `v0.90.74`.

I can confirm that we were notified at the following times:
* 2021-12-14 20:27:39
* 2021-12-14 23:27:39
* 2021-12-15 03:36:39

**Comment by adamboutcher** [comment]
you're expecting a status code of 200 but you're reciving a status code of 504 which is a gateway timeout. Is your service behind a reverse proxy?

We haven't changed this behaviour in the newer versions however v0.90.74 is before our fork.

**Comment by adamboutcher** [comment]
I'm also not sure if this is something we'd like to fix as status 200 is a plain success in http and anything else isn't what you'd expect from a working website unless it's configured otherwise.

Feel free to re-open to discuss more/my assumptions above are wrong.

**Comment by brunomiranda-hotmart** [comment]
Hi @adamboutcher yes you are correct in your assumptions.
But my point was more about the notify_after value rather than the error itself.
I have a configuration for notify_after with value 5, but after a single error my team and I are getting notified.

**Comment by adamboutcher** [comment]
OK, we'll try and look into this. Sorry I read your issue wrong.

**Comment by brunomiranda-hotmart** [comment]
Thanks @adamboutcher , just FYI, I couldn't reopen the issue, if you could do so.

**Comment by jemand771** [comment]
quick thought: this might be https://github.com/statping/statping/issues/911 which was fixed in https://github.com/statping-ng/statping-ng/pull/67, but that hasn't been released yet as far as I can see
(tl;dr: the notify after count feature would only work exactly once for each service and instantly retrigger after a fail -> success -> fail transition)
