### ISSUE TITLE
docker port change value broken atleast on unraid

### ISSUE THREAD

**Issue by viltie** [statping-ng/statping-ng#81]
At least when using this docker image in Unraid, web port value does not change the webserver port

There is the command it is executing:

```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Statping-ng' --net='br0' --ip='10.0.0.5' -e TZ="Europe/Kiev" -e HOST_OS="Unraid" -e HOST_HOSTNAME="R320" -e HOST_CONTAINERNAME="Statping-ng" -e 'TCP_PORT_8080'='80' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:8080]/' -l net.unraid.docker.icon='https://raw.githubusercontent.com/CorneliousJD/Docker-Templates/master/icons/statping.png' -v '/mnt/user/appdata/statping-ng':'/app':'rw' --user 99:100 'adamboutcher/statping-ng'
1188e35da2e293de6bc02ef488b149a488a720d45d55cb2ca5c60ec359f21910

The command finished successfully!
```

However, the port does not change. The webserver does not start on port 80, it starts on default 8080.

**Comment by adamboutcher** [comment]
Strange, we didn't change anything relating to that, what was the previous version you were running?

**Comment by viltie** [comment]
I'm new user, i don't know about the earlier version. This bug could have been here for a long time, not sure about what causes this.

**Comment by adamboutcher** [comment]
I'll take a look into how this works but this might be a slow fix

**Comment by adamboutcher** [comment]
Hi @viltie Try this:
`-e 'PORT=80'`
instead of 
`-e 'TCP_PORT_8080'='80'`

However port 80 is a privileged port and possibly also being used by unraid, so you might not be able to listen on it without fighting other processes, I'm not sure about unraid. Let me know if it doesn't work as we can poke a little more.

Tested:
```
adam@desktop:~$ docker run -e "PORT=8081" adamboutcher/statping-ng:dev
INFO[0000] Starting Statping v0.90.79                    type=cmd
INFO[0000] Statping HTTP Server running on http://0.0.0.0:8081/  type=handlers
```
and exposed
```
adam@desktop:~$ docker run -e "PORT=8081" -p 8081:8081 adamboutcher/statping-ng:dev
INFO[0000] Starting Statping v0.90.79                    type=cmd
INFO[0000] Statping HTTP Server running on http://0.0.0.0:8081/  type=handlers
```

Closing, if you have any more issues let us know and reopen.
