### ISSUE TITLE
Restarted Statping docker container always invokes setup page 

### ISSUE THREAD

**Issue by tilusnet** [statping-ng/statping-ng#87]
Hi.

I run Statping-ng in docker with a persisted volume:
```
docker run -d \
  -v statping_data:/app \
  adamboutcher/statping-ng
```
However, if I restart the container (or create a new one with the same volume attached), Statping always lands on the `/setup` page asking for basic info. It doesn't "remember" info on the setup page, I have to reenter it every time.
Can we persist data in the `/setup` page too?

FYI, this problem existed in the original [statping/statping](https://github.com/statping/statping) repo too.
I hope it can be fixed here.

Thanks!

**Comment by adamboutcher** [comment]
Sounds like your volume isn't being persisted. I only bind mount my docker volumes so I'm not 100% sure where the issue lies.

**Comment by tilusnet** [comment]
It looks persisted, because once I go past the setup page, all my previous services are there, as configured in the previous session.

It seems that the details on setup page are NOT kept inside `/app`. 
Can someone please check where the setup page details are written to?

@adamboutcher with your bind only config, what happens when you create a second container?
Does it make you land on the setup page or not? (it shouldn't)

**Comment by adamboutcher** [comment]
I bind to /app and if I scale or restart the container I never see the setup page...

**Comment by tilusnet** [comment]
Hmm that is very strange. 

I tried your config, with a new container, binding to a path on the host's filesystem - I get the same: upon container restart I get the setup landing page.

This is my `/app` content after a fresh container run:
```
-rwxr-xr-x 1 root    root          225 Dec 29 13:36 config.yml*
drwxr-xr-x 2 root    root        4,096 Dec 29 13:35 logs/
-rw-r--r-- 1 root    root    5,468,160 Dec 29 13:36 statping.db
```

Not sure how we are getting different behaviours.

@adamboutcher Do you mind sharing your container creation and restart commands?

**Comment by tilusnet** [comment]
I got as far as suspecting that the `core.App.Setup` boolean ends up being False [here in the code](https://github.com/statping-ng/statping-ng/blob/dev/handlers/index.go#L10). 
But where is this info persisted once the app started? Sadly I don't understand Go nor the framework Statping is using.

**Comment by adamboutcher** [comment]
I don't have my config available at the moment. But I'd assume it was stored in the database. I use postgres and not the default sqlite.

**Comment by tilusnet** [comment]
In the meanwhile I also tested with postgres. I used this config: https://github.com/statping-ng/statping-ng/wiki/Docker#docker-compose-with-nginx-and-postgres

And alas, no. 
It won't remember that Statping had been already setup. 
Once I restart the container, it redirects me to `hostname:port/setup`.

Where in the code is that `core.App.Setup` flag set? 
Is it indeed reading it from the database?

**Comment by tilusnet** [comment]
It would also be good to know which database table is checked.
I could browse the sqlite database file and check what needs to be there (and apparently isn't).

**Comment by adamboutcher** [comment]
Hi, to be honest, I've got no idea.

**Comment by twouters** [comment]
I've had the same issue, problem in my case were the `/app` directory permissions/ownership.
This code fails even though the directory is writable (the `config.yml` and `statping.db` are created successfully in a previous run): https://github.com/statping-ng/statping-ng/blob/251cac14de59567f4d3c6cfa4673c256b5fc1f34/types/configs/load.go#L42-L45

**Comment by adamboutcher** [comment]
feel free to re-open if this isnt fixed in version 0.90.80

**Comment by tilusnet** [comment]
Much appreciated @twouters, keen to test it.

@adamboutcher is the fix pushed to Docker Hub too?
I notice the [`dev`](https://hub.docker.com/layers/adamboutcher/statping-ng/dev/images/sha256-db4d11b9457af996111c8b40a6d77c009d8bfe608398013abb0085d157f21211?context=explore) tag updated yesterday but not `latest`.

**Comment by adamboutcher** [comment]
dev is the unstable build, which is currently 0.90.79, this fix is due in 0.90.80.

**Comment by tilusnet** [comment]
Hi again,
What's the estimated release date for 0.90.80?
Are there any milestones?

**Comment by aiciulian** [comment]
What's the estimated release date for 0.90.80?

**Comment by adamboutcher** [comment]
Hi Apologies for the delay in a reply... Please see https://github.com/statping-ng/statping-ng/issues/125 for updates.

**Comment by jirsbek** [comment]
Unfortunately this issue persists for me (tried quay.io/statping-ng/statping-ng:v0.90.80).
