### ISSUE TITLE
Tag new statping-ng/emails version as v1.0.2

### ISSUE THREAD

**Issue by jonathanrbarney** [statping-ng/statping-ng#9]
Golang still thinks the ng version of this depends on old version because it imports the old version of statping-emails. 

I'll attach a pull request with changes to import the new version of the emails package, but importing that package still wont work as you will get a:

```
go: github.com/statping-ng/statping-ng/notifiers imports
        github.com/statping-ng/emails: github.com/statping-ng/emails@v1.0.1: parsing go.mod:
        module declares its path as: github.com/statping/emails
                but was required as: github.com/statping-ng/emails
```

The code itself has been updated but golang dep management doesn't know to grab the new version since it fetches based off of version tags. Once you tag the repo with the new version it should be possible to add new version to the go.mod and go.sum

**Comment by adamboutcher** [comment]
Thanks for this :-)

**Comment by adamboutcher** [comment]
So this merge failed the build.. With the following error. 

`go: found github.com/statping-ng/emails in github.com/statping-ng/emails v1.0.1
go: github.com/statping-ng/statping-ng/notifiers imports
	github.com/statping-ng/emails: github.com/statping-ng/emails@v1.0.1: parsing go.mod:
	module declares its path as: github.com/statping/emails
	        but was required as: github.com/statping-ng/emails`

**Comment by jonathanrbarney** [comment]
Right sorry if i wasn't clear. You also have to tag the newest commits to the statping-ng/emails repo with the v1.0.2 tag

see [here](https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository) for how to if you haven't done that before

**Comment by jonathanrbarney** [comment]
After you do this you will probably want to run a `go mod tidy` and a `go get` to add the new dependency to the go.mod and go.sum files in the main statping repo then push the changes.

**Comment by adamboutcher** [comment]
> After you do this you will probably want to run a `go mod tidy` and a `go get` to add the new dependency to the go.mod and go.sum files in the main statping repo then push the changes.

running go mod tidy still brings the error, I've added a v1.0.2 tag on emails too.

**Comment by jonathanrbarney** [comment]
With some more changes to this and the emails repository, this module problem is resolved. Looks like there are some other issues with deployment and building, but this one is resolved.

**Comment by adamboutcher** [comment]
Awesome :-) The testing fails at the moment but as you say this issue is resolved :-)
