### ISSUE TITLE
Basic Auth Loop

### ISSUE THREAD

**Issue by capriciousduck** [statping-ng/statping-ng#93]
I've set a basic auth username and password. When I open the app and enter the site again asks for credentials - some sort of login loop.

**Comment by adamboutcher** [comment]
I'm aware of this issue but not figured it out yet...

**Comment by capriciousduck** [comment]
OK. Thanks for your reply.

**Comment by adamboutcher** [comment]
Notes:

Admin works
Users fail

User fails error 401 on checkins http request.

**Comment by attachmentgenie** [comment]
my analysis from last year still seems to hold true => https://github.com/statping/statping/issues/884#issuecomment-834213163
