### ISSUE TITLE
Strange Symbol?

### ISSUE THREAD

**Issue by UnclearGhostGT** [statping-ng/statping-ng#97]
![ICMP-Symbol](https://user-images.githubusercontent.com/61099339/149431930-aee789d7-aeec-4687-8065-2ab2bd37cfd1.PNG)

Strange symbol on my ICMP monitor? All my other ICMP monitors have the regular ms on it. Both monitors in the image above are ICMP and have the same configs.

Config in image. I'm running this in a docker instance.
![ICMP-Config](https://user-images.githubusercontent.com/61099339/149431799-2f0f1e6c-4167-407f-bcf4-738ca9ba4831.png)

**Comment by jemand771** [comment]
do you mean the `µs`? that's microseconds, with 1 µs being equal to 1000ms

**Comment by berezovskyi** [comment]
@UnclearGhostGT 47us = 0.047ms

**Comment by UnclearGhostGT** [comment]
> @UnclearGhostGT 47us = 0.047ms

Ohhh, okay i found it strange, my apololgies. I'll close this out, thanks.

**Comment by jemand771** [comment]
@berezovskyi thanks for the correction, not sure how I managed to mess this up ^-^
